### ISSUE TITLE
minindn issue

### ISSUE THREAD

**Issue by doctorhy** [signorello/NDN.p4#4]
Hello Salvatore,

(I found your posts in Issues #1 - #3  very useful. Thanks)
I could fortunately **find/solve the thrift problem** in "Issue 3", but still need your immediate help to fix the last-stage problems and run your experiment.
Actually, the problem with thrift is that it searches for file "ndn_router.json" which does not exist in your folder p4src. I have generated it using 
p4c-bmv2 --json JSON ndn_router.p4
and the error has gone. 

Now, to be on the same page, please first take a look at my next post which shows the terminal output.
As you can see, the **current issue** is that 
...... **"I don't start the application"** ....
(I am not sure this shows a problem, or only a message that you simply print in the output)
I also tested **ping** in the command line; it is not working because "network is unreachable".
Moreover, the file /tmp/a/packetPayload.txt is empty, which shows that the experiment could not run completely and successfully.

As I checked, even from outside your experiment, nfd is working well (by nfd-start and nfd-stop), mininet is working well (by mn -c and mn --test=pingall), but minindn is not working if "I don't start the application" shows an issue (**this surely happens after running your two patch files.** ); if not, I have no idea how to test minindn and/or what the problem is.

For double-checking (and also help the others to run your experiment), I
1- installed Ubuntu 14.04.5 LTS, and full packages of NDN and P4 (while running minindn v0.1.1).
2- run your two patch files in my main minindn directory
cd $MININDN_DIR; patch -p1 < $NDNP4_DIR/mini-ndn/mini-ndn.patch
cd $MININDN_DIR; patch -p1 < $NDNP4_DIR/mini-ndn/ndn_dir.patch
I also copied all your minindn directory files ($NDNP4_DIR/mini-ndn) to my main mininndn directory (in both $MININDN_DIR and $MININDN_DIR/ndn)
and then reinstalled minindn by ./install.sh -i
3- modified the paths in "p4-switch.conf" and copied it to "/usr/local/etc/mini-ndn/"
4- run python createFIBrules.py --fib fib.txt --cmd ndn_commands.partial.txt -c 5
5- generated json file to fix the thrift error using p4c-bmv2 --json JSON ndn_router.p4
6- run your experiment by 
sudo minindn $MININDN/p4.ndn.basic.conf --experiment=P4_NDN_experiment --p4
...

I'd really appreciate it if you could  
1- check all the steps as well as my next post to verify them (and let me know if I missed something to do),
2- check that you have uploaded all the required files for running your experiment.
Moreover, please let me know
3- does that message show a minindn issue? if not, how can I test minindn, and what is the problem?
4- should I use your "**nfd.conf**" uploaded in your main folder in anyway? (I tried to copy it to /usr/local/etc/ndn, but as I checked, after this commands nfd-start/stop is not working! I also tried to copy to /usr/local/etc/mini-ndn, but I found that nfd.conf in this folder is always replaced by running minindn, so I could not use your nfd.conf in this way as well).
FYI, as you mentioned in Issue #1, I also disabled all 3 IPv6 lines in /usr/local/etc/ndn/nfd.config (by "enable_v6 no;"); nothing new happens and still packetPayload.txt is empty! Should I apply more changes?

and finally help me to find and fix the problem.

Thanks.
Hamed

**Comment by doctorhy** [comment]
**Terminal output**

hamed@hamed:~/mini-ndn-0.1.1$ sudo minindn /home/hamed/mini-ndn-0.1.1/p4.ndn.basic.conf --experiment=P4_NDN_experiment --p4
No results folder specified; experiment results will remain in the working directory
Parse of /home/hamed/mini-ndn-0.1.1/p4.ndn.basic.conf done.
*** Creating network
*** Adding controller
*** Adding hosts:
a b 
*** Adding switches:
s1 
*** Adding links:
(a, s1) (b, s1) 
*** Configuring hosts
a b 
Setup time: 6
Reading config file  /usr/local/etc/mini-ndn//p4-switch.conf
/home/hamed/bmv2/targets/simple_switch/simple_switch /home/hamed/bmv2/targets/simple_switch/runtime_CLI /home/hamed/NDN.p4/p4src/ndn_router.json l3 9090 True True /home/hamed/NDN.p4/ndn_commands.partial.txt
*** Starting controller
c0 
*** Starting 1 switches
s1 Starting P4 switch s1
/home/hamed/bmv2/targets/simple_switch/simple_switch -i 1@s1-eth1 -i 2@s1-eth2 --pcap --thrift-port 9090 --nanolog ipc:///tmp/bm-0-log.ipc --log-console --device-id 0 /home/hamed/NDN.p4/p4src/ndn_router.json
Disable IPv6 forwarding on the P4Switch
switch has been started
Filling switch tables using /home/hamed/NDN.p4/ndn_commands.partial.txt
Control utility for runtime P4 table manipulation
RuntimeCmd: Setting default action of count_table
action:              storeNumOfComponents
runtime data:        00
RuntimeCmd: Adding entry to exact match table count_table
match key:           VALID-	VALID-	VALID-	VALID-	VALID-
action:              storeNumOfComponents
runtime data:        01
Entry has been added with handle 0
RuntimeCmd: Adding entry to exact match table count_table
match key:           VALID-	VALID-	VALID-	VALID-	VALID-
action:              storeNumOfComponents
runtime data:        02
Entry has been added with handle 1
RuntimeCmd: Adding entry to exact match table count_table
match key:           VALID-	VALID-	VALID-	VALID-	VALID-
action:              storeNumOfComponents
runtime data:        03
Entry has been added with handle 2
RuntimeCmd: Adding entry to exact match table count_table
match key:           VALID-	VALID-	VALID-	VALID-	VALID-
action:              storeNumOfComponents
runtime data:        04
Entry has been added with handle 3
RuntimeCmd: Adding entry to exact match table count_table
match key:           VALID-	VALID-	VALID-	VALID-	VALID-
action:              storeNumOfComponents
runtime data:        05
Entry has been added with handle 4
RuntimeCmd: Setting default action of hashName_table
action:              computeStoreTablesIndex
runtime data:        
RuntimeCmd: Adding entry to exact match table pit_table
match key:           EXACT-05
action:              readPitEntry
runtime data:        
Entry has been added with handle 0
RuntimeCmd: Adding entry to exact match table pit_table
match key:           EXACT-06
action:              cleanPitEntry
runtime data:        
Entry has been added with handle 1
RuntimeCmd: Setting default action of fib_table
action:              _drop
runtime data:        
RuntimeCmd: Adding entry to exact match table updatePit_table
match key:           EXACT-01
action:              updatePit_entry
runtime data:        
Entry has been added with handle 0
RuntimeCmd: Adding entry to exact match table updatePit_table
match key:           EXACT-00
action:              _drop
runtime data:        
Entry has been added with handle 1
RuntimeCmd: Adding entry to exact match table routeData_table
match key:           EXACT-01
action:              setOutputIface
runtime data:        00:00
Entry has been added with handle 0
RuntimeCmd: Adding entry to exact match table routeData_table
match key:           EXACT-02
action:              setOutputIface
runtime data:        00:01
Entry has been added with handle 1
RuntimeCmd: Setting default action of routeData_table
action:              _drop
runtime data:        
RuntimeCmd: Setting default action of send_packet_table
action:              _drop
runtime data:        
RuntimeCmd: Adding entry to exact match table send_packet_table
match key:           EXACT-00:01
action:              rewrite_macs
runtime data:        00:04:00:00:00:01	00:0a:00:00:00:01
Entry has been added with handle 0
RuntimeCmd: Adding entry to exact match table send_packet_table
match key:           EXACT-00:02
action:              rewrite_macs
runtime data:        00:04:00:00:00:02	00:0a:00:00:00:01
Entry has been added with handle 1
RuntimeCmd: Adding entry to ternary match table fib_table
match key:           EXACT-03	TERNARY-00:00 &&& 00:00	TERNARY-00:00 &&& 00:00TERNARY-7e:de &&& ff:ff	TERNARY-00:00 &&& 00:00	TERNARY-00:00 &&& 00:00
action:              set_egr
runtime data:        00:01
Entry has been added with handle 0
RuntimeCmd: Adding entry to ternary match table fib_table
match key:           EXACT-04	TERNARY-00:00 &&& 00:00	TERNARY-00:00 &&& 00:00TERNARY-7e:de &&& ff:ff	TERNARY-00:00 &&& 00:00	TERNARY-00:00 &&& 00:00
action:              set_egr
runtime data:        00:01
Entry has been added with handle 1
RuntimeCmd: Adding entry to ternary match table fib_table
match key:           EXACT-05	TERNARY-00:00 &&& 00:00	TERNARY-00:00 &&& 00:00TERNARY-7e:de &&& ff:ff	TERNARY-00:00 &&& 00:00	TERNARY-00:00 &&& 00:00
action:              set_egr
runtime data:        00:01
Entry has been added with handle 2
RuntimeCmd: Adding entry to ternary match table fib_table
match key:           EXACT-02	TERNARY-00:00 &&& 00:00	TERNARY-e7:30 &&& ff:ffTERNARY-00:00 &&& 00:00	TERNARY-00:00 &&& 00:00	TERNARY-00:00 &&& 00:00
action:              set_egr
runtime data:        00:02
Entry has been added with handle 3
RuntimeCmd: Adding entry to ternary match table fib_table
match key:           EXACT-03	TERNARY-00:00 &&& 00:00	TERNARY-e7:30 &&& ff:ffTERNARY-00:00 &&& 00:00	TERNARY-00:00 &&& 00:00	TERNARY-00:00 &&& 00:00
action:              set_egr
runtime data:        00:02
Entry has been added with handle 4
RuntimeCmd: Adding entry to ternary match table fib_table
match key:           EXACT-04	TERNARY-00:00 &&& 00:00	TERNARY-e7:30 &&& ff:ffTERNARY-00:00 &&& 00:00	TERNARY-00:00 &&& 00:00	TERNARY-00:00 &&& 00:00
action:              set_egr
runtime data:        00:02
Entry has been added with handle 5
RuntimeCmd: Adding entry to ternary match table fib_table
match key:           EXACT-05	TERNARY-00:00 &&& 00:00	TERNARY-e7:30 &&& ff:ffTERNARY-00:00 &&& 00:00	TERNARY-00:00 &&& 00:00	TERNARY-00:00 &&& 00:00
action:              set_egr
runtime data:        00:02
Entry has been added with handle 6
RuntimeCmd: Adding entry to ternary match table fib_table
match key:           EXACT-01	TERNARY-9c:dd &&& ff:ff	TERNARY-00:00 &&& 00:00TERNARY-00:00 &&& 00:00	TERNARY-00:00 &&& 00:00	TERNARY-00:00 &&& 00:00
action:              set_egr
runtime data:        00:03
Entry has been added with handle 7
RuntimeCmd: Adding entry to ternary match table fib_table
match key:           EXACT-02	TERNARY-9c:dd &&& ff:ff	TERNARY-00:00 &&& 00:00TERNARY-00:00 &&& 00:00	TERNARY-00:00 &&& 00:00	TERNARY-00:00 &&& 00:00
action:              set_egr
runtime data:        00:03
Entry has been added with handle 8
RuntimeCmd: Adding entry to ternary match table fib_table
match key:           EXACT-03	TERNARY-9c:dd &&& ff:ff	TERNARY-00:00 &&& 00:00TERNARY-00:00 &&& 00:00	TERNARY-00:00 &&& 00:00	TERNARY-00:00 &&& 00:00
action:              set_egr
runtime data:        00:03
Entry has been added with handle 9
RuntimeCmd: Adding entry to ternary match table fib_table
match key:           EXACT-04	TERNARY-9c:dd &&& ff:ff	TERNARY-00:00 &&& 00:00TERNARY-00:00 &&& 00:00	TERNARY-00:00 &&& 00:00	TERNARY-00:00 &&& 00:00
action:              set_egr
runtime data:        00:03
Entry has been added with handle 10
RuntimeCmd: Adding entry to ternary match table fib_table
match key:           EXACT-05	TERNARY-9c:dd &&& ff:ff	TERNARY-00:00 &&& 00:00TERNARY-00:00 &&& 00:00	TERNARY-00:00 &&& 00:00	TERNARY-00:00 &&& 00:00
action:              set_egr
runtime data:        00:03
Entry has been added with handle 11
RuntimeCmd: 


**I don't start the application
I don't start the application**
Loading experiment: P4_NDN_experiment
Printing eth0 faceID: 257

*** Starting CLI:
mininet> **a ping b**
connect: **Network is unreachable**
mininet>

**Comment by signorello** [comment]
Hi Hamed,
follow some answers for your questions:

- [I don't start the application]: this refers to the nlsr daemon (name-based routing protocol which is executed by default on ndn hosts in mini-ndn) which is not started on the nodes for the sake of this demo. As you pointed out, the message is a bit misleading and I am going to make it clearer.

- [failed ping]: this is normal since, first, you do not have any route bringing your IP packets from host a to host b in this demo, second, even if you added the rule (e.g., mininet> a ip route add 10.0.2.0/24 dev a-eth0), the packet will be then processed by the switch s1 (your p4 program) which do not contain the right logic to process those IP packets. You may try to explore this by yourself by first adding the routing entry to a, then pinging b and finally checking the switch log (at /tmp/p4s.s1.log).

- [installation steps]:  the steps seem to be correct.

- [nfd.conf]: I would rather change (disabling IPv6 as you've done) and use the nfd.conf which you have in your working env, since newer version of nfd may not be able (and crash) to parse older versions of nfd.conf. W.r.t. the replacement problem, I know it, I'd applied some local changes to my mini-ndn to overcome it and opened an issue on the mini-ndn repo to alert the dev-team this can cause problems.

I hope I've not missed any question,
Salvatore
