### ISSUE TITLE
mini-ndn v0.1.1 install error

### ISSUE THREAD

**Issue by zhangdongdongdong** [signorello/NDN.p4#5]
i notice the mini-ndn should be 0.1.1 of version ,and i follow the instruction from :https://github.com/named-data/mini-ndn/blob/v0.1.1/INSTALL.md  to install mini-ndn v0.1.1.
my step is as follows:
(1)i clone the mini-ndn v0.1.1
(2)use the code : $ sudo ./install.sh -mrfti  to install mini-ndn
(3)try to verficate the mini-ndn is well :
sudo minindn --pingall 50 --ctime 180 ndn_utils/hyperbolic_conf_file/minindn.caida.conf
but ,i got a lot of error.

the I change my step:
(1)i clone the mini-ndn v0.1.1
(2)i install the dependencies one by one,such as NFD,NLSR,ndn-tools
(3)use the code : $ sudo ./install.sh -i  to install mini-ndn
(4)try to verficate the mini-ndn is well :
sudo minindn --pingall 50 --ctime 180 ndn_utils/hyperbolic_conf_file/minindn.caida.conf
also ,i got a lot of error.

can you help me to fix this ? i am a new fresh to this ,if you can help,i will really appreciate it.

thank you,sincerely!

**Comment by signorello** [comment]
this is a mini-ndn installation problem, so it does not make much sense to keep an open thread here. You should better ask for some support on the mini-ndn mailing list, sorry I cannot help you with that.
Anyway let me cut&paste a few lines of advice before closing this issue:

"I would really suggest to clean any previous mini-ndn installed on your system, if the version number is not the same, and re-install the indicated version from scratch. You can get the right version of mini-ndn from the official repo by downloading the sources in tar format at
https://github.com/named-data/mini-ndn/releases
or by checking out the 0.1.1 tag from a terminal with
$ git clone https://github.com/named-data/mini-ndn.git
$ git tag -l (to see the available tags and get the right name to use with the next checkout cmd)
$ git checkout v0.1.1"

Hope you can fix it,
my best
